# Numpy Dizilerinde Koşullu Fonksiyonlar

Veri dünyasında önemli olan diğer konular ise verileri seçmek ve yönetmektir. Bu noktada numpy kütüphanesinin koşullu fonksiyonları büyük kolaylıklar sağlıyor.

<font color="Crimson"><br>
Bu kısımda şu metotları açıklayacağım:
<br><font color="BurlyWood"><br>
np.argwhere
<font color="BurlyWood"><br>    
np.where
<font color="BurlyWood"><br>    
np.select

In [1]:
import numpy as np

In [2]:
a = np.array([[2,4,6],[20,40,60]])

In [3]:
b = np.array([[1,3,5],[10,30,50]])

## np.argwhere

Bu fonksiyon koşulu sağlayan değerlerin indeksini verir.

b dizisinde 15'ten büyük değerlerin indekslerine erişelim.

In [4]:
np.argwhere(b>15)

array([[1, 1],
       [1, 2]], dtype=int64)

## np.where

Bir koşul dizisinin değerine bağlı olarak iki diziden değerleri seçer.

Fonksiyonun ilk parametresi koşul, ikinci parametresi koşul doğru olduğunda verinin çekileceği dizi/değer ve son parametresi koşul yanlış olduğunda verinin çekileceği dizi/değer.

a dizisinde 5'ten küçük olan değerleri 0 değeri ile değiştirelim. 

In [6]:
np.where(a<5,0,a)

array([[ 0,  0,  6],
       [20, 40, 60]])

a verisinin 4'e tam bölünen değerlerini b verisindeki aynı konumundaki değeri ile doldurulmasını yapalım.

In [7]:
np.where(a%4==0,b,a)

array([[ 2,  3,  6],
       [10, 30, 50]])

## np.select

Bu fonksiyonun np.where'den farkı, birden fazla koşulu işleyebilmesidir. Koşullar listesine bağlı olarak bir dizi listesinden değerleri seçer.

a dizisindeki elemanların 5'ten küçük olması durumunda 44 değerini alırken, 10'dan büyük olması durumunda değeri b dizisinden alan kodu yazalım.

In [8]:
sartlar = [a<5,a>10]

sartlar değişkenini oluşturma sebebim, durumlar adlı değişkendeki değerler, sartlar adlı değişkendeki koşulları sağladaığında sırasıyla hangi değerlerin geleceğini belirlemek içindir.

In [9]:
durumlar = [44,b]

Şartlarımızı ve bu şartlar sağlandığında gelen değerler ile oluşan diziye bakalım.

In [10]:
np.select(sartlar,durumlar)

array([[44, 44,  0],
       [10, 30, 50]])