# Numpy Dizileri Oluşturma

Numpy dizileri oluşturmak için temelde 2 yol vardır. 
    
    1.yol: Numpy kütüphanesinin içerdiği fonksiyonlar kullanılarak
    
    2.yol: Python'un sağlamış olduğu tuple ve list veri yapılarını Numpy fonksiyonlarında çağırarak.
    
## Numpy Kütüphanesini Kullanarak Numpy Dizilerini Oluşturma

### np.zeros

İstenilen boyut ve veri türüne göre 0 değeri ile dolu bir dizi oluşturmayı sağlar.

3 satır ve 2 sütundan oluşan 0 değerleri ile dolu bir dizi oluşturalım.

In [1]:
import numpy as np

In [2]:
data = np.zeros((3,2))

In [3]:
data

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

data isimli değişkenin boyutunu görüntüleyelim.

In [4]:
data.ndim

2

Yukarıda görüldüğü üzere data değişkeni 2 boyutludur.

Şimdi boyutlarının uzunluğuna erişelim.

In [5]:
data.shape

(3, 2)

Çıktıda görüldüğü üzere data değişkeni 3 satır ve 2 sütundan oluşmaktadır.

### np.ones

İstenilen boyut ve veri türüne göre 1 değeri ile dolu bir dizi oluşturmayı sağlar.

2 satır ve 3 sütundan oluşan 0 değerleri ile dolu bir dizi oluşturalım.

In [6]:
data = np.ones((2,3))

In [7]:
data

array([[1., 1., 1.],
       [1., 1., 1.]])

Çıktıda görüldüğü üzere data değişkeni sadece 1 değerlerinden oluşmaktadır.

data isimli değişkenin boyutuna erişelim.

In [8]:
data.ndim

2

Boyutlarının uzunluğuna erişelim.

In [9]:
data.shape

(2, 3)

### np.full

İstenilen boyut ve veri türüne göre bir dizi veya herhangi bir sayı ile dolu bir dizi oluşturur.

Bu fonksiyon ile np.zeros ve np.ones fonksiyonlarının yaptığı işlemi yaptırabilirsiniz fakat kullanım kolaylığı açısından np.zeros ve np.ones daha rahattır.

2 satır ve 2 sütundan oluşan içeriği 44 değeri ile dolu bir dizi oluşturalım.

In [10]:
data = np.full((2,2),44)

In [11]:
data

array([[44, 44],
       [44, 44]])

data isimli değişkenin boyutunu görüntüleyelim.

In [12]:
data.ndim

2

Boyutlarının uzunluğuna erişelim.

In [13]:
data.shape

(2, 2)

np.full fonksiyonu kullanarak np.zeros gibi sonuç elde edelim.

In [14]:
data = np.full((2,2),0)

In [15]:
data

array([[0, 0],
       [0, 0]])

In [16]:
data.ndim

2

In [17]:
data.shape

(2, 2)

np.full fonksiyonu kullanarak np.ones gibi sonuç elde edelim.

In [18]:
data = np.full((2,2),1)

In [19]:
data

array([[1, 1],
       [1, 1]])

In [20]:
data.ndim

2

In [21]:
data.shape

(2, 2)

### np.diag

Var olan bir numpy dizisinin köşegen boyunca belirtilen değerlere sahip bir köşegen dizi oluşturur ve kalan yerleri 0 ile doldurur. 

In [22]:
data

array([[1, 1],
       [1, 1]])

np.diag fonksiyonuna data değişkenini göndererek köşegenlerdeki değerleri alalım.

In [23]:
np.diag(data)

array([1, 1])

Şimdi ise köşeğen dışındaki değerleri sıfırlayalım.

In [24]:
np.diag(np.diag(data))

array([[1, 0],
       [0, 1]])

### np.eye

İstenilen boyut ve veri türüne göre belirtilen köşegen boyunca bir değerleri ile köşegen dizisi oluşturur ve kalan yerleri sıfır ile doldurur.

np.diag fonksiyonu ile oldukça benzerdir. Farkları ise np.eye fonksiyonunda köşegen değerlerin istediğimiz değer ile değilde 1 değeri ile dolduruluyor olmasıdır.

In [25]:
data = np.eye(3,3)

In [26]:
data

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
data.ndim

2

In [28]:
data.shape

(3, 3)

### np.arange

İstenilen başlangıç, bitiş ve artış değerleri arasında eşit aralıklı değerlere sahip bir dizi oluşturur.

3 değerinden başlayarak 11'e kadar 2'şer artan değerlerden oluşan bir dizi oluşturalım.

In [29]:
data = np.arange(start=3, stop=11, step=2)
data

array([3, 5, 7, 9])

### np.linspace

İstenilen sayıda element kullanarak, belirtilen başlangıç ve bitiş değerleri arasında eşit aralıklı değerlere sahip bir dizi oluşturur.

3 değerinden başlayarak 11'e kadar 5 değer içeren bir dizi oluşturalım.

In [30]:
data = np.linspace(start=3, stop=11, num=5)
data

array([ 3.,  5.,  7.,  9., 11.])

### np.random.rand

0 ile 1 arasında eşit olarak dağıtılan rastgele sayılarla bir dizi oluşturur.

Rastgele üretilen sayıları sabitlemek için np.random.seed fonksiyonu kullanılır. Eğer bu fonksiyon ile sabitleme yaparsak rastgele üretilen değerler sabitlenir ve her çağırdığımızda aynı sayılar üretilir.

Rastgele değişkenleri her seferinde aynı oluşturması np.random.seed değerini 0'a sabitleyelim.

In [31]:
np.random.seed(0)  #0 değerli sabitleme

2 satır ve 3 sütundan oluşan içerisi rastgele değerler ile dolu bir dizi oluşturalım.

In [33]:
data = np.random.rand(2,3)

In [34]:
data

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411]])

In [35]:
data.ndim

2

In [36]:
data.shape

(2, 3)

### np.empty

İstenilen boyut ve veri türüne göre dizinin değerleri başlatılmadan rastgele değerler ile dolu bir dizi oluşturmayı sağlar.

In [37]:
data = np.empty([2,2]) 

In [38]:
data

array([[8.10607782e-312, 3.36652529e-289],
       [4.60469182e-321, 1.37929727e-312]])

In [39]:
data.shape

(2, 2)

## Var Olan Python List Veya Tuple Dosyalarını Kullanarak Numpy Dizisi Oluşturma

### np.array

Elementleri, örneğin iç içe geçmiş bir python listesi, bir tuple, iteratif bir dizi veya başka bir ndarray örneği olabilen bir dizi benzeri nesnesinden bir Numpy dizisi oluşturur.

Şimdi bir python listesinden numpy dizisi oluşturalım.

data isimli bir değişkenin 1,2 ve 3 değerlerini içeren bir numpy dizisi oluşturmasını sağlayalım.

In [40]:
data = np.array([1,2,3])

In [41]:
data

array([1, 2, 3])

Şimdi iç içe geçmiş bir python listesinden numpy dizisi oluşturalım.

In [42]:
data = np.array([[1,2], [3,4]])

Yukarıda 2 tane python listesini içeren bir numpy dizisi oluşturulmuştur.

In [43]:
data

array([[1, 2],
       [3, 4]])

In [44]:
data.shape

(2, 2)

In [45]:
data.ndim

2

Şimdi bir python tuple nesnesinden numpy dizisi oluşturalım. Bir tuple içerisine 1,2,3 değerlerini ekledikten sonra np.array fonksiyonuna gönderelim.

In [46]:
data = np.array((1,2,3))

Tuple yapısından oluşan numpy dizisine bakalım.

In [47]:
data

array([1, 2, 3])

Çıktıda görüldüğü üzere standart bir numpy dizisi oluşmuştur.