# Numpy Dizilerini İndeksleme Ve Dilimleme

Numpy dizilerinin öğelerine ve alt dizilerine, Python listelerinde de kullanılan standart köşeli ayraç gösterimi kullanılarak erişilir.

## Tek boyutlu dizilerde indeksleme ve dilimleme operasyonları

Şimdi durumların daha iyi anlaşılabilmesi amacıyla bir uygulama gerçekleştirelim.

9 ile 99 aralığında 10 sayı oluşturalım.

In [1]:
import numpy as np

In [2]:
data = np.linspace(start=9, stop=99, num=10)

In [3]:
data

array([ 9., 19., 29., 39., 49., 59., 69., 79., 89., 99.])

Dizinin ilk elemanına erişelim.

In [4]:
data[0]

9.0

Dizinin son elemanına erişelim.

In [5]:
data[-1]

99.0

Dizinin 3.elemanına erişelim. İndeks 0'dan başladığı için 3.eleman 2.indekste yer almaktadır.

In [6]:
data[2]

29.0

Dizinin 2. ile 4.indeksler aralığındaki değerlere erişelim.

In [7]:
data[2:5]

array([29., 39., 49.])

Dizide belli bir element aralığına erişebilmek için [başla:bitir:adım_uzunluğu] yapısını kullanmalıyız.

Sıfırıncı indeksten başlayarak 2'şer ilerleyerek yedinci indekse kadarki değerlere erişelim.

In [8]:
data[0:7:2]

array([ 9., 29., 49., 69.])

## Çok boyutlu dizilerde indeksleme ve dilimleme operasyonları

Bir örnek ile anlayalım. 1'den 12'ye kadar değerleri içeren 3 satır 4 sütundan oluşan bir dizi oluşturalım.

In [9]:
data = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [10]:
data

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
data.ndim

2

In [12]:
data.shape

(3, 4)

Dizinin ilk sütununa erişelim.

In [13]:
data[:,0]

array([1, 5, 9])

Dizinin ikinci indeks sütununa erişelim.

In [14]:
data[:,2]

array([ 3,  7, 11])

Dizinin ilk satırına erişelim.

In [15]:
data[0,:]

array([1, 2, 3, 4])

Dizinin ikinci indeks satırına erişelim.

In [16]:
data[2,:]

array([ 9, 10, 11, 12])

Dizide belli bir element aralığını seçmek için [başla:bitir:adım_uzunluğu, başla:bitir:adım_uzunluğu] yapısı kullanılır.

Sıfırıncı satır indeksinden başlayarak iki adım ile son satır indekse kadar olan ve sıfırıncı sütun indeksinden başlayarak üç adım ile son sütun indeksine kadar arada kalan değerlere ulaşmak için [0:3:2,0:4:3] yapısı kullanılır.

In [17]:
data[0:3:2,0:4:3]

array([[ 1,  4],
       [ 9, 12]])