## Numpy Veri Tipleri

Bir Numpy dizisi homojen olmak zorundadır. Homojen tabirinden kasıt, dizi içndeki elementlerin veri tiplerinin aynı olması durumudur. Veri tipleri tamsayı, işaretsiz tamsayı, mantıksal ifade, ondalıklı sayı, karmaşık sayı olabilmektedir.

Burada bu veri tiplerini açıklayacağım.

### Tamsayılar

Tam sayı verileri bu tip ile tutabiliriz. En sık kullanılan tamsayı formları int8, int16, int32, int64'tür. Bu formlar verinin değeri büyüdükçe kullanılır.

Şimdi np.array kullanarak bir tamsayı verisi üretelim.

In [4]:
import numpy as np

# warning 
import warnings
warnings.filterwarnings('ignore')

In [5]:
data = np.array([1,2,300], dtype=np.int)
data

array([  1,   2, 300])

data isimli değişkenin veri tipine bakalım.

In [7]:
data.dtype

dtype('int32')

### İşaretsiz Tamsayılar

Eğer veri setinde negatif tamsayı içeren bir veri yoksa bu formatı kullanarak bilgisayardaki belleği daha etkili kullanabiliriz. En sık kullanılan işaretsiz tamsayı formları uint8, uint16, uint32, uint64. 

### Mantıksal İfadeler

Eğer veri setinde True veya False gibi ifadeler var ise bu formatı kullanarak bilgisayardaki belleği daha etkili kullanabiliriz.

np.array metodunun dtype parametresine np.bool ifadesini atayarak mantıksal bir dizi oluşturabiliriz. Bu işlemi gerçekleştirelim.

In [8]:
data = np.array([-1,0,1,6], dtype=np.bool)
data

array([ True, False,  True,  True])

0 rakamına False değeri verilir ve diğer rakamlara True değeri verilir. Çıktıda [-1,0,1,6] dizisine karşılık gelen mantıksal dizi görülmektedir.

Şimdi data isimli mantıksal değerler içeren dizinin veri tipine bakalım.

In [9]:
data.dtype

dtype('bool')

### Ondalıklı Sayılar

Eğer veri seti ondalıklı değerler içeriyorsa bu formatı kullanarak bilgisayardaki belleği daha etkili kullanabiliriz. En sık kullanılan işaretsiz tamsayı formları float16, float32, float64, float128'dir.

np.array metodunun dtype parametresine np.float ifadesini atayarak ondalıklı bir dizi oluşturabiliriz. Bu işlemi gerçekleştirelim.

In [10]:
data = np.array([10,20,30], dtype=np.float)
data

array([10., 20., 30.])

Float tipine çevrim söz konusu olduğu için tamsayı değerlerin sonunda nokta bulunmaktadır.

Şimdi dizinin veri tipine bakalım.

In [11]:
data.dtype

dtype('float64')

### Karmaşık Sayılar

Eğer veri seti karmaşık sayılar içeriyorsa bu formatı kullanarak reel(real) ve imajiner(j,imag) kısımları rahatlıkla gerçekleştirebiliriz.

np.array metodunun dtype parametresine np.complex ifadesini atayarak bir dizi oluşturabiliriz. Bu işlemi gerçekleştirelim.

In [12]:
data = np. array([-1,0,1], dtype=np.complex)
data

array([-1.+0.j,  0.+0.j,  1.+0.j])

Çıktıda görüldüğü üzere j değerlerini dizide belirtmediğimiz için j'nin katsayıları sıfır almıştır.

Eğer reel kısım bir imajiner kısım içermiyorsa 0 katsayısı ile j (imajiner) kısmı eklenir.

Şimdi dizinin veri tipine bakalım.

In [13]:
data.dtype

dtype('complex128')

Dizide bulunan elemanların reel kısımlarını ekrana yazdıralım.

In [14]:
data.real

array([-1.,  0.,  1.])

Dizide bulunan elemanların imajiner kısımlarını ekrana yazdıralım.

In [15]:
data.imag

array([0., 0., 0.])