# Numpy Dizilerinde Temel Aritmetik Operasyonlar

Numpy dizileri ile yapılan temel aritmetik işlemler eleman bazlı gerçekleşir.

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
b = np.array([10,20,30])
b

array([10, 20, 30])

In [4]:
c = a+b
c

array([11, 22, 33])

In [5]:
c = a-b
c

array([ -9, -18, -27])

In [6]:
c = a*b
c

array([10, 40, 90])

In [7]:
c = a/b
c

array([0.1, 0.1, 0.1])