# Numpy Dizilerinde Eleman Bazlı Fonksiyonlar

Eleman bazlı fonksiyonlar girdi olarak verilen numpy dizisine uygulandıklarında aynı boyuta sahip yeni bir dizi döndürür. Bu fonksiyonlar girdi dizisindeki bütün elementlere ayrı ayrı uygulanır.

<font color="DodgerBlue"><br>
Bu kısımda anlatacağım metotlar şu şekildedir:
<font color="Chocolate"><br>
np.exp
<font color="Chocolate"><br>
np.sqrt
<font color="Chocolate"><br>
np.log
<font color="Chocolate"><br>
np.cos
<font color="Chocolate"><br>
np.sin

In [2]:
import numpy as np

In [5]:
a = np.array([4,16,64])

## np.exp

Dizideki x değerlerinin her biri için e^x değerini hesaplar.

In [6]:
np.exp(a)

array([5.45981500e+01, 8.88611052e+06, 6.23514908e+27])

## np.sqrt

Dizideki tüm elementlerin karekökünü hesaplar.

In [7]:
np.sqrt(a)

array([2., 4., 8.])

## np.log

Dizideki tüm elementlerin e tabanında logaritmasını hesaplar.

In [8]:
np.log(a)

array([1.38629436, 2.77258872, 4.15888308])

## np.cos

Dizideki tüm elementlerin değerlerini radyan cinsinden kabul edip kosinüs değerini hesaplar.

In [9]:
np.cos(a)

array([-0.65364362, -0.95765948,  0.39185723])

## np.sin

Dizideki tüm elementlerin değerlerini radyan cinsinden kabul edip sinüs değerini hesaplar.

In [10]:
np.sin(a)

array([-0.7568025 , -0.28790332,  0.92002604])