# Numpy Dizilerinin Manipülasyonu

Verilerle çalışırken, numpy dizilerini yeniden düzenlemek, şeklini değiştirmek önemlidir. Numpy kütüphanesi bu manipülasyon için bir takım metotlar barındırır. 

<font color="Chocolate"><br>
Burada anlatacağım metotlar şu şekildedir:
<font color="CadetBlue"><br>
np.append
<font color="CadetBlue"><br>
np.delete
<font color="CadetBlue"><br>
np.ndarray.transpose
<font color="CadetBlue"><br>
np.ndarray.reshape
<font color="CadetBlue"><br>
np.ndarray.flatten
<font color="CadetBlue"><br>
np.concatenate
<font color="CadetBlue"><br>
np.vstack
<font color="CadetBlue"><br>
np.hstack

## np.append

Numpy dizisine eleman eklemek için bu metottan yardım alınabilir.

Şimdi bir dizi oluşturalım ve append metodu ile diziye eleman ekleyelim.

In [1]:
import numpy as np

In [2]:
data = np.array([1,2,3])

In [3]:
data

array([1, 2, 3])

np.append metodu ile data isimli diziye 4,5 ve 6 değerlerini ekleyelim.

In [4]:
new_data = np.append(data,[4,5,6])

In [5]:
new_data

array([1, 2, 3, 4, 5, 6])

## np.delete

Numpy dizisindeki belirli bir konumdaki elemanı indeks bilgisi ile siler.

data isimli dizi içerisinden 0.indeksteki elemanı silelim.

In [8]:
data

array([1, 2, 3])

In [6]:
new_data = np.delete(data,0)

In [7]:
new_data

array([2, 3])

## np.ndarray.transpose

Numpy dizisinin transpozunu almamızı sağlar.

2 satır ve 3 sütundan oluşan bir numpy dizisi oluşturalım. Sonrasında bu dizinin transpozunu alalım.

In [9]:
data = np.array([[1,2,3],[4,5,6]])
data

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
data.shape

(2, 3)

In [11]:
new_data = np.ndarray.transpose(data)
new_data

array([[1, 4],
       [2, 5],
       [3, 6]])

In [12]:
new_data.shape

(3, 2)

## np.ndarray.reshape

Dizinin satır ve sütun sayısını değiştirmek istersek bu metodu kullanabiliriz.

In [15]:
data = np.array([[1,2,3,4,5,6]])
data

array([[1, 2, 3, 4, 5, 6]])

In [16]:
data.shape

(1, 6)

Görüldüğü üzere oluşturduğumuz dizi 1 satır 6 sütundan oluşmaktadır.

Şimdi data dizisini 2 satır ve 3 sütundan oluşacak şekilde yeniden şekillendirelim.

In [18]:
new_data = np.ndarray.reshape(data,(2,3))
new_data

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
new_data.shape

(2, 3)

Görüldüğü üzere 2 satır ve 3 sütundan oluşacak şekilde şekil almıştır.

## np.ndarray.flatten

np.ndarray.flatten, np.ndarray.rehsape fonksiyonunun özel bir halidir. Dizinin tek boyuta indirgenmesini sağlar.

In [20]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [22]:
data.shape

(2, 2)

In [21]:
new_data = np.ndarray.flatten(data)
new_data

array([1, 2, 3, 4])

In [23]:
new_data.shape

(4,)

Görüldüğü üzere veri tek boyuta indirgenmiştir.

## np.concatenate

Belirli bir eksen boyunca dizileri birbiri ardına ekleyerek yeni bir numpy dizisi oluşturur.

In [24]:
a = np.array([[1,2],[3,4]])

In [25]:
a

array([[1, 2],
       [3, 4]])

In [26]:
b = np.array([[5,6],[7,8]])

In [27]:
b

array([[5, 6],
       [7, 8]])

np.concatenate metodu ile a ve b isimli dizileri alt alta birleştirelim.

In [28]:
c = np.concatenate((a,b),axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

np.concatenate metodu ile a ve b isimli dizileri yan yana birleştirelim.

In [29]:
d = np.concatenate((a,b),axis=1)
d

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## np.vstack

Dİkey olarak numpy dizilerini yığınlar. Yani dizilerin alt alta birleştirilmesini sağlar. 

In [30]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [31]:
b = np.array([10,20,30])
b

array([10, 20, 30])

In [32]:
c = np.vstack((a,b))

In [33]:
c

array([[ 1,  2,  3],
       [10, 20, 30]])

## np.hstack

Yatay olarak numpy dizilerini yığınlar. Yani dizilerin yan yana birleştirilmesini sağlar. 

In [34]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [35]:
b = np.array([10,20,30])
b

array([10, 20, 30])

In [36]:
c = np.hstack((a,b))

In [37]:
c

array([ 1,  2,  3, 10, 20, 30])